import os
import time
from github import Github
from typing import Tuple
from flask.cli import load_dotenv

# Load environment variables from .env
load_dotenv()

# Load GitHub token
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
if not GITHUB_TOKEN:
    raise RuntimeError("GITHUB_TOKEN not set in environment")

# Authenticate with GitHub
gh = Github(GITHUB_TOKEN)

# MIT license template
MIT_LICENSE_TEXT = """MIT License

Copyright (c) {year} {owner}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

... (standard MIT license body) ...
"""

def create_or_update_repo(repo_name: str, index_html: str, readme_md: str, license_owner: str) -> Tuple[str, str, str]:
    """
    Create a public repo or update it if it exists.
    Returns: (repo_html_url, commit_sha, pages_url)
    """
    user = gh.get_user()
    print("🔍 Authenticated GitHub user:", user.login)

    # Normalize repo name
    repo_name = repo_name.replace(" ", "-").lower()
    print("🔍 Target repo name:", repo_name)

    # Try to fetch existing repo
    try:
        repo = user.get_repo(repo_name)
        print("🔍 Repo exists:", repo.html_url)
    except Exception as e:
        print("🔍 Repo fetch failed, creating new repo:", e)
        repo = user.create_repo(name=repo_name, private=False, description="Auto-generated by student API")
        time.sleep(2)  # Give GitHub time to register the new repo

    # Helper to create or update a file
    def upsert_file(path: str, message: str, content: str):
        try:
            existing = repo.get_contents(path)
            repo.update_file(path, message, content, existing.sha)
            print(f"✅ Updated {path}")
        except Exception as e:
            print(f"🔍 Creating {path}: {e}")
            repo.create_file(path, message, content)
            print(f"✅ Created {path}")

    # Push files
    upsert_file("index.html", "Add index.html", index_html)
    upsert_file("README.md", "Add README", readme_md)
    license_text = MIT_LICENSE_TEXT.format(year=time.localtime().tm_year, owner=license_owner)
    upsert_file("LICENSE", "Add MIT license", license_text)

    # Get latest commit SHA
    commits = repo.get_commits()
    commit_sha = commits[0].sha if commits.totalCount > 0 else ""

    # Construct GitHub Pages URL
    pages_url = f"https://{user.login}.github.io/{repo.name}/"

    return repo.html_url, commit_sha, pages_url
