import os
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, EmailStr
from typing import List, Dict
import uuid
import base64

from gemini_utils import generate_code_snippet
from github_utils import create_or_update_repo
from notify_eval import notify_evaluation

load_dotenv()  # loads .env

app = FastAPI(title="Student API - LLM Code Deployment (Student side)")

class Attachment(BaseModel):
    name: str
    url: str

class TaskRequest(BaseModel):
    email: EmailStr
    secret: str
    task: str
    round: int
    checks: List[str]
    evaluation_url: str
    attachments: List[Attachment] = []

def _expected_secret_for(email: str) -> str:
    safe_email = email.replace("@", "_").replace(".", "_")
    key = f"SECRET_FOR_{safe_email}"
    return os.getenv(key)


def _sanitize_task_name(task: str) -> str:
    return task.replace(" ", "-").lower()

@app.post("/api-endpoint")
async def handle_task(req: TaskRequest):
    expected = _expected_secret_for(req.email)
    if expected is None or req.secret != expected:
        raise HTTPException(status_code=403, detail="Invalid secret")

    # Nonce generation (uuid4 used; substitute with uuid7 if available)
    nonce = str(uuid.uuid4())

    # Compose prompt for Gemini to generate a minimal static app (index.html)
    # Keep prompt focused and instruct to include README and comments
    prompt = (
        f"You are a helper that writes minimal static web projects. "
        f"Task brief: {req.task}\n"
        f"Checks: {req.checks}\n"
        f"Attachments: {[(a.name) for a in req.attachments]}\n\n"
        "Generate a single-file `index.html` (or minimal supporting files inline) that satisfies the checks. "
        "Also generate a README.md explaining how the page works and where the code is. "
        "Output only two sections separated clearly: "
        "### INDEX_HTML_START then the raw HTML then ### INDEX_HTML_END; "
        "### README_START then the README contents then ### README_END."
    )

    gen_output = generate_code_snippet(prompt)

    # Try to extract sections generated by the model
    index_html = None
    readme_md = None
    if "### INDEX_HTML_START" in gen_output and "### INDEX_HTML_END" in gen_output:
        try:
            index_html = gen_output.split("### INDEX_HTML_START", 1)[1].split("### INDEX_HTML_END", 1)[0].strip()
        except Exception:
            index_html = None
    if "### README_START" in gen_output and "### README_END" in gen_output:
        try:
            readme_md = gen_output.split("### README_START", 1)[1].split("### README_END", 1)[0].strip()
        except Exception:
            readme_md = None

    # Fallback simple content if extraction failed
    if not index_html:
        index_html = f"""<!doctype html>
<html>
<head><meta charset="utf-8"><title>{req.task}</title></head>
<body>
  <h1>{req.task}</h1>
  <p>Auto-generated minimal page. Checks: {req.checks}</p>
</body>
</html>"""

    if not readme_md:
        readme_md = f"# {req.task}\n\nAuto-generated README.\n\nChecks: {req.checks}\n"

    repo_name = _sanitize_task_name(req.task)
    try:
        repo_url, commit_sha, pages_url = create_or_update_repo(repo_name, index_html, readme_md, license_owner=req.email)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GitHub operation failed: {e}")

    payload = {
        "email": req.email,
        "task": req.task,
        "round": req.round,
        "nonce": nonce,
        "repo_url": repo_url,
        "commit_sha": commit_sha,
        "pages_url": pages_url,
    }

    try:
        notify_evaluation(req.evaluation_url, payload)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed to notify evaluation service: {e}")

    return {"status": "success", "repo_url": repo_url, "pages_url": pages_url, "commit_sha": commit_sha}
